cask_args appdir: '/Applications', require_sha: true

brew 'mas'

# Core/high-priority dependencies

cask '1password'
cask 'google-chrome'
cask 'iterm2'
cask 'ghostty'
cask 'karabiner-elements'
cask 'raycast'
cask 'rectangle'

# Command line apps

brew 'bat'
brew 'fd'
brew 'findutils'
brew 'fish'
brew 'fnm'
brew 'fzf'
brew 'git'
brew 'git-lfs'
brew 'gh'
brew 'gping'
brew 'grip'
brew 'htop'
brew 'jq'
brew 'lnav'
brew 'm-cli'
brew 'ncdu'
brew 'neovim'
brew 'nmap'
brew 'ossp-uuid'
brew 'pam-reattach'
brew 'php'
brew 'pyenv'
brew 'python'
brew 'ranger'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'sqlite'
brew 'stow'
brew 'tldr'
brew 'tmux'
brew 'tree'
brew 'watchman'
brew 'wget'
brew 'yarn'

# Desktop apps

cask 'gpg-suite-no-mail'
cask 'hiddenbar'
cask 'pictogram'
cask 'spotify'
cask 'tower'
cask 'visual-studio-code'
mas 'iA Writer', id: 775737590
mas 'Microsoft To Do', id: 1274495053

# Personal
# cask 'discord'
# cask 'notion'
# cask 'transmission'
# cask 'vlc'
# mas 'NordVPN', id: 905953485
# mas 'OneDrive', id: 823766827
# mas 'WhatsApp Desktop', id: 1147396723

# Image utils
# brew 'imagemagick'
# brew 'optipng'

# JDK
# cask 'adoptopenjdk/openjdk/adoptopenjdk17'

# Android
# cask 'android-sdk'
# cask 'android-studio'
# cask 'android-platform-tools'
# brew 'pidcat'

# Backend dev
# brew 'composer'
# brew 'confd'
# brew 'docker'
# brew 'docker-compose'
# brew 'mailhog'

# Other dev apps
# brew 'fastmod'
# brew 'graphviz'
# cask 'keycastr'
# cask 'postico'
# cask 'postman'
# cask 'sequel-ace'
