code --install-extension brian-anders.sublime-duplicate-text
code --install-extension britesnow.vscode-toggle-quotes
code --install-extension dbaeumer.vscode-eslint
code --install-extension github.copilot
code --install-extension jdinhlife.gruvbox
code --install-extension editorconfig.editorconfig
code --install-extension esbenp.prettier-vscode
code --install-extension malmaud.tmux
code --install-extension marp-team.marp-vscode
code --install-extension mikestead.dotenv
code --install-extension pnp.polacode
code --install-extension mk12.better-git-line-blame
code --install-extension ryuta46.multi-command
code --install-extension sleistner.vscode-fileutils
code --install-extension usernamehw.errorlens
code --install-extension wmaurer.change-case
