code --install-extension brian-anders.sublime-duplicate-text
code --install-extension britesnow.vscode-toggle-quotes
code --install-extension dbaeumer.vscode-eslint
code --install-extension dinhlife.gruvbox
code --install-extension eamodio.gitlens
code --install-extension editorconfig.editorconfig
code --install-extension esbenp.prettier-vscode
code --install-extension malmaud.tmux
code --install-extension marp-team.marp-vscode
code --install-extension mikestead.dotenv
code --install-extension pnp.polacode
code --install-extension sleistner.vscode-fileutils
code --install-extension wmaurer.change-case
