tapall rcmdnk/file

tap homebrew/core
tap homebrew/services
tap homebrew/cask

brew awscli
brew bat
brew clang-format
brew confd
brew docker
brew docker-compose
brew fd
brew ffmpeg
brew findutils
brew fish
brew fzf
brew git
brew git-lfs
brew gh
brew gnu-sed
brew graphviz
brew grip
brew htop
brew icdiff
brew imagemagick
brew jq
brew lnav
brew m-cli
brew mailhog
brew neofetch
brew neovim
brew nmap
brew optipng
brew ossp-uuid
brew php
brew python
brew ranger
brew reattach-to-user-namespace
brew sc-im
brew sqlite
brew stow
brew terminal-notifier
brew the_silver_searcher
brew tldr
brew tmux
brew tree
brew vim
brew watchman
brew wget
brew yarn

cask google-chrome
cask 1password
cask alfred
cask authy
cask discord
cask dozer
cask firefox
cask flipper
cask glance
cask gpg-suite-no-mail
cask gimp
cask graphiql
cask hyperswitch
cask iterm2
cask karabiner-elements
cask keybase
cask keycastr
cask monitorcontrol
cask musescore
cask notion
cask onedrive
cask pocket-casts
cask postico
cask postman
cask react-native-debugger
cask sequel-ace
cask slack
cask spectacle
cask spotify
cask sublime-text
cask tower
cask telegram
cask transmission
cask visual-studio-code
cask vlc
cask whatsapp

appstore 937984704 Amphetamine
appstore 775737590 iA Writer
appstore 1274495053 Microsoft To Do
appstore 1278508951 Trello
appstore 497799835 Xcode

# Android SDK
cask adoptopenjdk/openjdk/adoptopenjdk8
cask android-sdk
cask android-studio
cask android-platform-tools
