# - Common configuration -

source-file ~/.tmux-common.conf

# - Plugins -

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# - Plugin options -

set -g @yank_action 'copy-pipe'

set -g @scroll-without-changing-pane on
set -g @scroll-speed-num-lines-per-scroll 2

set -g @resurrect-capture-pane-contents 'on'

# - Local options -

set -g default-command 'fish; exit'

# - Local key bindings -

bind r source-file ~/.tmux.conf

# - Platform-specific -

if-shell 'test "type -q xclip"' 'set -g @override_copy_command "xclip -selection clipboard -i"'
if-shell 'test (uname) = "Darwin"' 'source ~/.tmux-macos.conf'

run -b '~/.tmux/plugins/tpm/tpm'
