# Common tmux configuration shared across environments

# - Options -

set -g default-terminal 'xterm-256color'
set -ga terminal-overrides ",xterm-256color:Tc"
set -ga terminal-overrides ",xterm-ghostty:Tc"

set -g default-shell $SHELL

set -g set-titles on
set -g set-titles-string '#T'
set -g base-index 1

set-option -g mouse on
set-option -s -g escape-time 1
set-option -g renumber-windows on
set-option -g history-limit 10000

set-window-option -g mode-keys vi

# - Appearance -

set -g status-left ''
set -g status-right ''
set -g status-style bg=default

setw -g window-status-separator ' '
setw -g window-status-format '#[fg=#665c54] #I #[fg=#7c6f64] #W '
setw -g window-status-current-format '#[bg=#3d3836,fg=#a1967d] #I #[fg=#f6eeda]#{?window_zoomed_flag,#[bg=#458588],} #W '

set -g pane-border-style fg="#3D3836"
set -g pane-active-border-style fg="#e0e0e0"

# - Key bindings -

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind _ split-window -vb -c "#{pane_current_path}"

bind-key -n S-Up set-option -g status
bind-key -n S-Down set-option -g status

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# - Copy mode bindings (vi-style) -

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
